dataclasses_json/core.py
tests/entities.py
tests/test_api.py
tests/test_generics.py

Fix bugs around logic for guessing types and filling nones
Add warnings during decode when dealing with missing / None
Add tests

Additional fixes and improvements related to infer-missing

---

setup.py

Fixing Pipenv by pinning marshmallow.

---

dataclasses_json/core.py
tests/entities.py
tests/test_api.py
tests/test_generics.py

Fix decoding dataclass fields with default factory

---

dataclasses_json/core.py
tests/entities.py
tests/test_api.py
tests/test_generics.py

Add dict codec and small refactor

---

dataclasses_json/api.py
dataclasses_json/mm.py
tests/entities.py
tests/test_api.py
tests/test_examples.py

Add infer missing argument to `.schema()`

---

dataclasses_json/core.py
tests/test_enum.py

* Added support for enum.Enum and included unit tests.
* Fixed unittest that was previously commented out

WIP Add support for Enum (#51)

---

dataclasses_json/mm.py

Fix typo in instantation

---

dataclasses_json/core.py

Fix restoring objects with non-constructor argument field

---

dataclasses_json/api.py
dataclasses_json/core.py
dataclasses_json/mm.py
setup.py
tests/test_annotations.py
tests/test_api.py

Api additions: `to_dict` and `from_dict`

---

README.md

Noticed the first example didn't run when you copy and paste it; this resolves that.

Ensure first section in README.md runs without modifications

---

dataclasses_json/mm.py
tests/test_schema.py

Fix #121 
Check for letter_case and update data_key if needed

Enhance schema generation with data_key

---

Pipfile
Pipfile.lock
README.md
tests/test_recursive.py

Added a small example of self-recursion in the README.

Added test case for self-recursion with Marshmallow Schema

---

Pipfile
Pipfile.lock
dataclasses_json/mm.py
setup.py
tests/test_annotations.py
tests/test_union.py

Hello, thank you for create and maintain amazing package.
would you review my pull request?
- New parameter "many" was added. 35f6f4c286241e7dec1fcbeb9912b02b3b4887ba
https://github.com/marshmallow-code/marshmallow/commit/35f6f4c286241e7dec1fcbeb9912b02b3b4887ba
https://github.com/marshmallow-code/marshmallow/pull/1220
- Dump validation was removed. a3e95aeaaab9ec649cda80ede73793f471531cc0
https://github.com/marshmallow-code/marshmallow/commit/a3e95aeaaab9ec649cda80ede73793f471531cc0
https://github.com/marshmallow-code/marshmallow/pull/1304

Follow marshmallow's update

---

dataclasses_json/core.py

Fixs #144
Extend the special case in Collection handeling that was already present for str to also apply to byte strings.

Fix _asdict converting bytes to list of int

---

publish.py

Fix deprecation warnings due to invalid escape sequences.

---

README.md

Remove incorrect/old code in example

Correct Example for Different name Encode/Decode

---

dataclasses_json/core.py
tests/entities.py
tests/test_nested.py

suggested fix for https://github.com/lidatong/dataclasses-json/issues/294

fix: decoding nested dicts with tuple keys

---

dataclasses_json/__init__.py

Quick fix for #290 , waiting for full typing support

explicit export of the imported name

---

dataclasses_json/core.py

Would love your feedback on this solution
Closes #311

bug: override encoding before _asdict

---

index.html

fixing link

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

Resolves #414. Add formalized issue template for this repo.
- [Bug report](https://github.com/lidatong/dataclasses-json/blob/ci/add_issue_template/.github/ISSUE_TEMPLATE/bug_report.yaml)
- [Feature request](https://github.com/lidatong/dataclasses-json/blob/ci/add_issue_template/.github/ISSUE_TEMPLATE/feature_request.yaml)

feat: add formalized issue template

---

dataclasses_json/api.py

Fixes #402 
Since this only adds a type hint, not much to do about it. We'll be implementing type hints separately though, see #412

Fix autocomplete when using annotation

---

.github/workflows/pythonpackage.yml
README.md

When I finally learn to remember `|` in workflow scripts, world hunger will be solved.

Fix multiline scripts in CI

---

dataclasses_json/api.py

Revert type hint in annotation call

---

.github/workflows/pythonpackage.yml

Temporarily disable code coverage publish for fork PRs
