lidatong/dataclasses-json

dataclasses_json/api.py, setup.py
This parameter was removed from recent Marshmallow version, and was the reason for the error in #18 .
Removing this parameter should allow upgrading Marshmallow again.
=> Remove `prefix` from Marshmallow constructor

setup.py
The latest version fixes the memory leak issue
described in #26
=> Unpin and upgrade marshmallow

dataclasses_json/api.py, dataclasses_json/core.py, tests/test_metadata.py
This adds support for passing the Marshmallow fields directly to the dataclass.
This is done via the dataclass field metadata: e.g.:
```python
@dataclass
class Car(DataClassJsonMixin):
license_number: str = field(metadata={'mm': fields.String(required=False)})
```
The metadata field takes priority over the dataclass type.
I probably forgot a bunch of edge cases, so please review it care 😁
=> Add support for passing the MM fields directly

dataclasses_json/mm.py, tests/entities.py, tests/test_api.py, tests/test_collections.py
This change fixes the issues discussed in #45 where default value boolean fields using marshmallow schema.  Unit tests were added to confirm the problem has been fixed.
=> Bug fix for default bool when using schema

dataclasses_json/mm.py
Original bug most likely created when refactoring. ```cls``` variable changed to ```dataclass_json_cls```.
=> Fix broken warning message

dataclasses_json/core.py, tests/test_enum.py
This change allows the package to convert JSON to ```enum.Enum``` utilizing the type hint of the dataclass field. The *.value property of an Enum is used when encoding JSON. Unit tests to validate these changes are included and follow the same structure @lidatong has been using in existing code.. 
``` python
from enum import Enum
from dataclasses import dataclass
from dataclasses_json import dataclass_json
class MyEnum(Enum):
STR1 = "str1"
INT1 = 1
@dataclass_json
@dataclass
class DataWithEnum:
name: str
my_enum: MyEnum
x = DataWithEnum.from_json('{"name": "name2", "my_enum": "str1"}')
assert x.my_enum == MyEnum.STR1
```
=> Add support for Enum

dataclasses_json/api.py, dataclasses_json/core.py, dataclasses_json/mm.py, tests/entities.py, tests/hypothesis2/strategies.py, tests/test_api.py, tests/test_schema.py, tests/test_time.py
In light of #68 I have updated the code to fix #57, #58, #60, #65, #67 and #68. I have added relevant tests and ensured they pass in Python 3.6 and 3.7. (I've changed the code to allow skipping of the datetime tests.)
From this I have moved all schema code into `mm` so that the marshmallow code is contained. And this is basically just a re-write of `mm`. I've updated `api` to accommodate these changes.
Otherwise only `core` has been changed. This is because marshmallow now loads schema data into the relevant model. (This can be tested against with code in #58). I'm unsure how you'd want the data to be handled, and so I chose to return early so I don't mangle with `core` too. **please verify this is the intended behavior**.
This should keep all the previous logic around options, most are …
=> Fix schema problems

dataclasses_json/core.py, tests/test_enum.py
Fixes #75.
Move up the enum check in _decode_generic to ensure that enums are decoded
properly regardless of any mixin classes.
`MyEnum(str, Enum)` was handled incorrectly as collection before, for
example.
=> Fix decoding of enums with mixins

dataclasses_json/api.py, dataclasses_json/core.py
Hello,
This PR is meant to resolve issue #69. The problem is that overrides for encoding are only called at the top level, meaning any nested dataclasses do not have their configured overrides applied to them. By moving the `_overrides` and `_override` methods into `_asdict` the recursive calls to each of the fields in the nested dataclasses get their overrides applied.
I'm happy to apply any changes you see fit, and perhaps add some regression tests to ensure this recursive encoding behaviour is recorded.
=> Reorder extraction to allow recursive encoding overrides to work

README.md, dataclasses_json/core.py, tests/test_recursive.py
Resolve ForwardRef from type hints.
I think there’s a bug with `dataclasses.fields()`. It probably should resolve forward references. Until then `typing.get_type_hints()` can return resolved types.
=> Allow forward references

dataclasses_json/mm.py, setup.py, tests/test_enum.py
- New Enums will be handled (or processed) as EnumField in marshmallow schema
- Added unit tests
=> Marshmallow enum support (#51) (#63) (#83)

README.md, dataclasses_json/api.py, dataclasses_json/mm.py, tests/test_annotations.py, tests/test_examples.py
- Fixed type annotation for `DataClassJsonMixin.from_json()`: was `A -> A`, now `Type[A] -> A`.
- Fixed invalid example in ReadMe (one with Tutor)
- Extended possible argument types for all `loads()` methods (including `from_json()`): was `str`, now `Union[str, bytes, bytearray]`. This now matches the `json.loads()` prototype.
- Added `class SchemaHelper[T]`, which provides type annotations for generated schemas.
- `DataClassJsonMixin.schema()` is now `Type[A] -> SchemaHelper[A]`
- Added tests for type annotations: `test_annotations.py`. They start mypy and check the current file.
- Added tests for Tutor in `test_example.py`
- #91: Invalid code example in ReadMe
- #88: Doubt regarding Type Annotation in "from_json"
If you have any doubts in `test_annotations.py`, try changing any type …
=> Fixes for type annotations

dataclasses_json/core.py, dataclasses_json/mm.py, setup.py, tests/test_union.py
- Added new class _UnionField for handling typing.Union (in the serialized data of the classes listed in the Union[...], a new field "__type" will appear)
- Added unit tests
Note:
Only works through the use of the "schema" field:
```
schema = <dataclass>.schema()
schema.dump(<dataclass_instance>)  # for serialization to python dict
schema.dumps(<dataclass_instance>)  # for serialization to json
```
and 
```
schema = <dataclass>.schema()
schema.load(<py_dict>)  # for serialization from python dict
schema.loads(<json_str>)  # for serialization from json
```
`<dataclass>.to_json(<dataclass_instance>)` and `<dataclass>.from_json(<json_str>)` methods are not affected because to_json method does not use marshmallow.
=> Union type support (#82)

dataclasses_json/api.py, dataclasses_json/mm.py, setup.py, tests/test_annotations.py, tests/test_api.py
Sometimes, you already have loaded json (i.e., from the function result, from json5, from yaml, etc.)
This will help to avoid such construction:
```python
loaded: dict = json5.load(my_opened_file)
data: MyDataclass = MyDataclass.from_json(json.dumps(loaded))
```
Of course, you can always use schema loaders, but there are still redundant calls:
```python
data: MyDataclass = MyDataclass.schema().load(loaded)
```
- Added overload for api.from_json() - it now accepts dict in addition to str, bytes and bytearray
- Added api and annotation tests covering this scenario.
- Other minor fixes/improvements:
- `mm.py`: Minor type annotation issue fixed
- Annotation Tests: added support for mypy of 0.710+
- `setup.py`: now mypy of 0.710+ is required
=> Added support for from_json() accepting dict in addition to str-like types

dataclasses_json/api.py, dataclasses_json/core.py, dataclasses_json/mm.py, tests/test_letter_case.py
Fixes schema generation #107 and allows setting raw `field_name` #116 #110 #115
JSON-type encodable `to_dict()` #118
=> Fix Marshmallow schema generation for `letter_case` allow `field_name`

dataclasses_json/mm.py, tests/test_union.py
Prevents impact on the original serialized data during Union deserialization.
Previously, the field “__type” was being removed from the original data, which made it impossible to deserialize from the original data twice.
=> Union support bugfix

README.md, dataclasses_json/__init__.py, dataclasses_json/api.py, dataclasses_json/core.py, tests/entities.py
Addresses #128 
feat: make @dataclass_json take optional args and remove @configured_dataclass_json
BREAKING CHANGE: removes the `configured_dataclass_json` decorator in
favor of a unified `dataclass_json` decorator with optional args
=> feat: make @dataclass_json take optional args and remove @configured_dataclass_json

dataclasses_json/api.py, tests/test_letter_case.py
Added `PASCAL` to LetterCase. This allows you to serialise/deserialise json such as `{"GivenName": "Alice"}`
Pascal casing is popular in .NET microservices (Newtonsoft JSON.NET uses it as a standard strategy).
=> Adding pascal casing as lettercase option

README.md
`from_json` doesn't accept a dict, so I changed it to a string to match the above quickstart example.
=> Fix a readme typo

README.md
I thought it would be good to add an example in the readme to close #110 and demonstrate why you'd want to use it. 
side note: In my original case I wanted to integrate with a poorly named external json-api but didn't want to use the wacky names that they used. 
edit: Also seems like a good readme example for #117, #123
=> Add field_name example to readme

dataclasses_json/mm.py
I _think_ this change should fix #108 and #146 by adding a `None` check, and throwing a `ValidationError` in the case of a blank value showing up when it's not allowed according to the schema. As best as I can tell, this is what Marshmallow does in this sort of situation.
=> Optional support

setup.py
With this change, mypy can find dataclasses_json and can make use of its type annotations.
=> Enable mypy to find dataclasses_json when installed

dataclasses_json/api.py
I was excited to find out that https://github.com/lidatong/dataclasses-json/pull/150 was now available, but I ran into some issues when updating our projects.
Here are a few fixes for them:
1. Change callable to Callable (this could likely be improved further but I'm not too familiar with what should be the exact constraints)
2. Add type information to `DataClassJsonMixin.to_dict`
=> Fix a couple issues with api type hints

README.md, dataclasses_json/__init__.py, dataclasses_json/api.py, dataclasses_json/core.py, dataclasses_json/mm.py, dataclasses_json/utils.py, tests/test_annotations.py, tests/test_undefined_parameters.py
I implemented customizable behaviors when a dataclass_json object encounters keyword parameters during initialization that are not defined as fields.
The following snipped has also been added to the README, and there are several testcases for everything.
It works with `schema()` as well as `to_dict(), from_dict()` and `__init__`.
Closes #94 
By default, it is up to implementation what happens when a `json_dataclass` receives input parameters that are not defined.
(the `from_dict` method ignores them, when loading using `schema()` a ValidationError is raised.)
There are three ways to customize this behavior.
Assume you want to instantiate a dataclass with for the following dictionary:
```python
dump_dict = {"endpoint": "some_api_endpoint", "data": {"foo": 1, "bar": "2"}, …
```
=> Customizable behavior for undefined parameters

README.md
Changed `nunbers` -> `numbers`.
=> Fix README typo in the "Supported types" section

dataclasses_json/core.py, dataclasses_json/mm.py, dataclasses_json/utils.py, tests/entities.py, tests/test_schema.py
Direct response to #166.
This MR fixes 2.5 issues:
1) - A field that was typed as `Any` did not accept `None` values, it does now.
- A field that was typed as `Any` raised a warning that `Any` is an unknown type. `Any` is now mapped to `fields.Raw` and no longer raises the warning.
2) Nested `Optional` values were not passed on correctly to the schema, resulting in a `ValidationError` when passing `None`, even if the type allowed it (e.g. `Dict[str, Optional[int]]` did not allow optional values). It works now.
=> Fix nested optional type when loading from schema

dataclasses_json/api.py
Modifies 'DataClassJsonMixin' class methods to accept a customized JSON econder/decoder function.
Would be great this modification, in my case I can use `orjson` lib instead default Python default lib.
=> Customized JSON econder/decoder function

dataclasses_json/core.py, setup.py, tests/conftest.py, tests/fixtures.py, tests/test_cache.py
* Same as https://github.com/lidatong/dataclasses-json/pull/148 but with cachetools and correct caching
id should work for caching as the three functions in questions always will receive a class as an argument which will have same identity always. Tests are passing and I added some too.
Load test with cache_size=1:
```
It took 39.030911922454834s to convert to dict
It took 30.857404708862305s to convert from dict
```
After introducing caching:
```
It took 41.651854038238525s to convert to dict
It took 16.02430510520935s to convert from dict
```
So about a 2x speedup when converting from dict.
I did write a load_test and profiled it to get to those results. There is great improvement but as you can see with the graph the performance is still quite bad for encoding to the dict. I was trying …
=> add caching, add tests

dataclasses_json/api.py
The docstring was referring `Lettercase.CAMEL` instead of `LetterCase.CAMEL`. 
I lost 5 minutes on this as my IDE couldn't import the enum, so I though it might be worth fixing for others.
=> Fix dataclass_json docstring

dataclasses_json/core.py, tests/test_letter_case.py
Closes #160 
This PR prioritizes the field-level metadata overrides so that classes such as the following work as expected:
```python
@dataclass_json(letter_case=LetterCase.CAMEL)
@dataclass
class CamelCasePersonWithOverride:
given_name: str
years_on_earth: str = field(metadata=config(field_name='age'))
```
=> Fix field name override when letter_case is set with the decorator

dataclasses_json/__init__.py, dataclasses_json/cfg.py, dataclasses_json/core.py, tests/test_exclude.py
Introduce an `encode_action` field config parameter. When set to exclude
a field, the encoder will not include it in the encoded dictionary.
The config parameter can also accept a callback that receives the
key-value pair being encoded, allowing for more-granular control of the
exclusion check.
I'm very much open to modifying this to fit the goals of the library.  Also, I'm not sure how one goes about updating the documentation, but, if you point me in the right direction, I'm more than happy to update it as well.
Fixes #200
=> Allow fields to be excluded from encoding

dataclasses_json/core.py
Hello! I have a fairly large dataset (~7 million entries) that I am deserializing with this library, but unfortunately deserialization has become a bottleneck. After a bit of profiling, it looks like the majority of runtime is spent in `_user_overrides_or_exts` within `core.py`. More specifically, `_user_overrides_or_exts` creates a `FieldOverride` `NamedTuple` every time the method is called.
While the namedtuple creation may seem trivial, the runtime adds up when deserializing a large dataset. Below is a sample from my `cProfile` run:
```    Ordered by: cumulative time
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
7171820    8.270    0.000 5588.569    0.001 schema.py:691(load)
7171820   45.781    0.000 5580.299    0.001 schema.py:807(_do_load)
7171820   15.652 …
```
=> Move FieldOverrides creation outside of _user_overrides_or_exts

dataclasses_json/core.py, dataclasses_json/utils.py, setup.py, tests/test_unsupported_generics.py
- Added tests to detect #300 (two fail on Python 3.6)
* Unsupscripted Generics
* Supscripted Generics
* Parameterized Generics in Unsupscritped Generic class
* Parameterized Generics in Supscritped Generic class
- Updated dev dependencies to install `types-dataclasses` for Python 3.6 (to fix Annotations tests)
- Updated `_decode_dataclass` to use `_isinstance_safe` instead of simple `isinstance`
- Added TypeError handler for `_hasargs` function
=> Fix unsupported generics for Python 3.6

dataclasses_json/mm.py
Without it, getting a schema from a type including `typing.Tuple` returns a warning (as `typing.Tuple.__origin__` is `tuple`).
=> Add `tuple` to the list of fields.

tests/test_annotations.py
Closes #335
MyPy added a parameter `clean_exit` which must be set to `True` in order to intercept `SystemExit`.
That lead to the pytest process exiting after executing the first ever test (because annotations are alphabetically first).
=> Annotations test: Add `clean_exit=True` for `mypy_main()`

dataclasses_json/__init__.py, dataclasses_json/api.py, dataclasses_json/cfg.py
Closes #286
- `LetterCase` class moved from `.api` to `.cfg` (imported in `.api` for backwards-compatibilty
- `dataclasses_json.cfg.config()` now explicitly accepts either `Callable[...]` or `LetterCase` for parameter `letter_case`
- `dataclasses_json.cfg.config()` now explicitly accepts either `Callable[...]` or `Exclude` for parameter `exclude`
=> Explicitly allow dataclasses_json.cfg.config() argument letter_case to accept LetterCase members

dataclasses_json/core.py, dataclasses_json/utils.py, tests/entities.py, tests/test_collections.py, tests/test_unsupported_generics.py
Closes #341
* Updated `tests.entities` and `tests.test_collections` to include alternative forms of the same collection types
(like `builtins.list` ("builtin") and `typing.List` (~~"generic"~~ "unbound") in addition to the existing `typing.List[TypeA]`)
* Added new internal helper class ~~`core._NoArgs`~~ `utils._NoArgs` and its singleton instance ~~`core._NO_ARGS`~~ `utils._NO_ARGS`
* Added new methods ~~`core._extract_args()`~~ `utils._get_type_args()` and ~~`core._extract_type_parameter()`~~ `utils._get_type_arg_param()` which return either `tp.__args__` value or `_NO_ARGS` constant
* All "unsafe" usages of `tp.__args__` replaced with the new methods
* Added `TypeVar` special case check for `core._decode_dict_keys()`
- *Note:* This is a special case for Python 3.7 and Python 3.8.
By …
=> #341: Fixes for type-parameters without arguments

tests/test_annotations.py
Last month, a **mypy** change was released that made all arguments for the `mypy.main` method **keyword** only. They also removed an unused argument. 
https://github.com/python/mypy/pull/13399
The alternative to this change is to freeze your version of `mypy`
=> Update usage of mypy.main in test following updates to mypy package

dataclasses_json/core.py, tests/test_enum.py
Fixes #391, please refer to this issue for a detailed description of what is fixed in this pull request.
I implemented both a fix to the encoding and added tests that will capture the behaviour.
=> Fixes recursive dict encoding

README.md
The "Extended" section in the documentation has the wrong example. This fixes the example so that it uses `global_config` as mentioned in #181
=> Documentation: added example of global_config

dataclasses_json/core.py, tests/test_builtins.py, tests/test_invariants.py, tests/test_letter_case.py, tests/test_str_subclass.py
* Adding improved instantiation logic for `str`, `int`, `float` in dataclass decoder. 
* Fixing bugs in test code 
There are a few reasons why instantiating using the intended type when they are one of the three is beneficial. 
1. **Support for custom `str` classes is covered.** Previously this was not supported as `str` is treated special in the decode logic. This is further documented here: https://github.com/lidatong/dataclasses-json/issues/348
2. **Improved support for conversion from input X -> `int`|`float`**. Previously, values that represented numeric values (either stringified numeric values or `Decimal` objects) were not converted properly into the intended field type. So a dataclass field specified as an `int` would not decode `"42"` or `decimal.Decimal("42")` as `42`. This …
=> Add support for enhanced builtin instantiation

dataclasses_json/api.py, dataclasses_json/mm.py
Type arguments for a generic type alias must be provided at every use site, or the missing arguments will default to `Any`, which gives no type safety.
Fixes #370.
=> Restore `schema()` type safety by fixing generic type alias misuse

dataclasses_json/mm.py
The default_factory is a factory for generating the default value. For example, to get a default of `[]`, the default_factory will be `list`.
Without calling the factory, the schema will be filled with, in this case, `"<class: 'list'>"`. Whereas if you call the factory, the default will correctly be set to `[]`.
=> Fix: default_factory returned without being called when filling default value in schema

.github/workflows/pythonpackage.yml, dataclasses_json/mm.py, tests/entities.py, tests/test_api.py, tests/test_schema.py
When generating a marshmallow schema for a dataclass, fields that have no default value or default factory should be marked as required, so that when deserializing an object into the dataclass, a missing value for the field will result in a proper Validation error instead of a KeyError.
=> #395: fields with no default value/factory should be marked as required when generating schema

dataclasses_json/core.py, tests/entities.py, tests/test_nested.py
=> fix: surface nested mapping errors

dataclasses_json/core.py, dataclasses_json/stringcase.py, tests/test_letter_case.py
As described in #376, the camelCase serialization does not remove underscores in front of numbers. I believe it should - let me know what you think.
=> Fixes bug in string case serialization not taking numbers into account

dataclasses_json/cfg.py
* The `exclude` callback takes one argument, not two.
* Objects of type `Exclude` are not accepted. `ALWAYS` and `NEVER` have type `Callable`, not `Exclude`.
* Class variables like `Exclude.ALWAYS`, `Exclude.NEVER` are not allowed to be generic, and they don’t need to be, since `Callable[[object], bool]` is convertible to `Callable[[T], bool]`.
=> Fix config(exclude=…) type annotations

Pipfile, dataclasses_json/mm.py, setup.py
According to #380 this PR drops [marshmallow-enum](https://github.com/justanr/marshmallow_enum) dependency, which is now an archive. 
Enum type is supported since marshmallow 3.18.0.
=> Drop marshmallow-enum dependency

dataclasses_json/core.py, tests/test_enum.py
=> Fixes recursion bug related to enum flags

README.md
Closes #90 and #352 
I apologize for the commit message. I forgot to change it before comitting.
=> Add documentation for how to use with Numpy and Pandas

dataclasses_json/api.py
Use `typing.overload` to differentiate the return type of `dataclass_json` based on whether `_cls` parameter is `None` or not.
[This is motivated by fixing type issues in flytekit, which does not only use `dataclass_json` as a decorator](https://github.com/flyteorg/flytekit/blob/6acc97b91851b2e9c139d73ed763a085a53b32b0/flytekit/core/type_engine.py#L1550).
```python
from dataclasses import dataclass
from dataclasses_json.api import dataclass_json
@dataclass
class Point:
x: int
y: int
directly_wrapped = dataclass_json(Point)
reveal_type(directly_wrapped)
indirectly_wrapped = dataclass_json()(Point)
reveal_type(indirectly_wrapped)
####################################################################################################
@dataclass_json
@dataclass
class Point2:
x: int
y: int …
```
=> Improve dataclass_json and _process_class type annotations

pyproject.toml
Following the conventions I discovered/documented [here](https://daniel.feldroy.com/posts/2023-08-pypi-project-urls-cheatsheet) on the next PyPI release this adds links that make it easier for consumers of this project to see what changes may have occurred.
Thanks for the project!
=> Add links to make PyPI a better maintainer reference

dataclasses_json/core.py, dataclasses_json/mm.py, tests/test_union.py
This pull request adds a best-effort deserialization to Union types when no `__type` field specifier is present.
In the case that no `__type` field is present, a warning is issued describing the risk of such unmarshalling attempt.
We attempt to decode ensuring that keys exist on the type, and the values are appropriate.  If either of these conditions fails, we abandon that dataclass type, and move onto the next one.
If no type is found, a warning is issued, the value is not decoded, and is left as-is.
=> improve Union deserialization when "__type" field specifier is not present

dataclasses_json/undefined.py
This PR addresses Issue #382
@george-zubrienko I understand that you had not planned to tackle this issue before v1 and am aware of the discussions in Issue #458 as well.
As mentioned by @USSX-Hares, there's a possibility PEP-649 ends up superseding PEP-563. However, [a decision still has to be made](https://mail.python.org/archives/list/python-dev@python.org/message/VIZEBX5EYMSYIJNDBF6DMUMZOCWHARSO/)
In the meantime, the inability to use `CatchAll` is a major blocker for the full adoption of `dataclasses_json` in my team as we
rely heavily on type hints and have no other option but to postpone their evaluation through `from __future__ import annotations`.
The proposed solution relies on `typing.get_type_hints()` (as suggested by @estyxx) instead of `field.type` (whose type depends on …
=> fix: allow using CatchAll with postponed evaluation of annotations

dataclasses_json/api.py
Given our code:
```python
from dataclasses import dataclass
from dataclasses_json import DataClassJsonMixin, LetterCase, config
camelCaseConfig = config(letter_case=LetterCase.CAMEL)["dataclasses_json"]
@dataclass()
class MyDataStructure(DataClassJsonMixin):
dataclass_json_config = camelCaseConfig
name: str
```
Running mypy yields the following error:
> error: Incompatible types in assignment (expression has type "dict[Any, Any]", base class "DataClassJsonMixin" defined the type as "None")  [assignment]
The type is "defined as None" because no explicit type is given when initializing the variable. 
This PR provides the correct explicit type for `dataclass_json_config`.
=> fix mypy error when assigning to dataclass_json_config

dataclasses_json/core.py
Fixes #491 
I believe one way to fix this is to simply narrow down use cases for hetero tuples to either types == elements in tuple, or a single type :)
=> Fix an issue introduced with hetero tuple decode

dataclasses_json/core.py, tests/test_union.py
The type of union that failed is documented in the test I added, but basically if members of a union differed by the type of a field with a matching name, the resultant `AttributeError` wasn't being caught and so deserialization would stop and not all the members of the union would be tried
=> fix: fix deserialization of unions if the type of a field with the same name differs between union members

dataclasses_json/core.py, tests/test_global_config.py, tests/test_union.py
Use the encoder/decoder registered in the global configuration
=> fix: apply global config globally

dataclasses_json/core.py, dataclasses_json/utils.py, tests/test_generic_dataclass.py
=> fix: support generic dataclass

dataclasses_json/core.py
@rtsscy here you go. Thanks for noticing!
=> fix: comment from review

dataclasses_json/core.py, tests/test_core.py
This type annotation resolution is a flawed implementation -- ideally a
proper fix can come later, but for now it's worth warning about the
present behavior.
`dataclasses-json` does not behave correctly when using string-style
annotations (a frequent tactic for annotating types that have not yet
been defined at that point in the file).
The core problem comes from the assumption that type annotations in a
module will match `sys.modules()` -- `maybe_resolved` will frequently
resolve to a different value than a typechecker would!
A short example of the error
============================
`example_types.py`:
```python
from dataclasses import dataclass
from dataclasses_json import dataclass_json
@dataclass_json
@dataclass
class Config:
options: list["Option"]
@dataclass_json
@dataclass
class …
```
=> Warn about buggy type resolution
